language: node_js
sudo: false
node_js:
- '6'
cache: yarn
notifications:
  slack:
    secure: P3d36qfC1cM/0G03VqZXrjbWT1ByBePul+0QAIykrG2H9UUBZpt/OQTNJWHdzMvtJKRE5vFllckDGdJZCJO5OSlczQz7w1QUhTqrK3iTP/FClHpW2qyl+PfTUXEsl0lVQMotoNEk6MOsGJEgrY7CkzEObkGE53QmWmwojXvKJn+5AGsz14f0lXvfqTep4M96GyAZlye7Xm3DHenBTGoemlkIhA+yl6ua6SVefwm3/XD90ZyYz+YOK6hCrVJIrMDrp7zVZ1w88QPcoYupduhghIAh7wjbMjSGxikzQYNbWcvrwgzevAK9JKNfflKyWnu4zppaYL2zO9gyE3eZlN2eSpHsKi9VM4FlM04ZK82YLVHeWZBKMm4Pj4jde2yDqax+AJnFDW0zeYJk/XU7NV2DByyFFzzd70bStUu1HilCC7A9NM4EgVVxHrsx8ubpOMFcsOew1Ow8qLC9N96gTazkXfCosic2uxUreF++mGzXQBfv4kgIiUw1p3uZ2QlqcjYbdvHv2Uo8CQMG2s4dcO55Rzd47bnYqudwqXzcDBwdung+5WrbM3llygpDl+mnS7eguH4DX95AspX7eiL1+QDgiqoqZQwt6iulXfyBpJVnAA7NrrJNDXkIGACDnKjJFhvpaZET5TbZQYp/2MA4hN/h/hASlQDkvDr/Nx2NKOMH+bc=
services:
- postgresql
before_script:
- psql -a -U postgres -c 'create database travis;'
- bash migrations/migration_001.sh
deploy:
  provider: heroku
  api_key:
    secure: 1Y3mkIv2aIzeT57M68/Deus2PNyumMlMLXExb4n6WlFy2mchRlEHxhQBlWJSTg+9Q+yaTAmfswsFXrp0fXc/w0lCmY12YgVjPwQ4rcjhfpo90tztpWqKoHc9+SxXnFX8PZC4eZoulzFWcgY56mrEagrTAenYNd2wsP96/d89QsbjXQuqWCPvvKcdl33UNcodT3EtL1KvJ6UZ37YbnVbcSi0sHli7DLwCZH+WsawTy9kuLQ7EMdjoCYJmv4/XVNlMAxwIaLFqMbTLN7kWbqQa5v28ghDVPV2d4e5sE4aGYvv37wdGnWlhNRJppq79XG/NY90urna+27aowb2VZww4zs/TtrUXH0aMYmrIHkuZIpDjrpYog1D7RkV59Y3/6A9VKslu+tz0N8A1rzYzYA2IsIuRu3L4fcNXB3p2Hl4GNKmMXb1aTE1VEFpJLUVa7hLEEp9ByUDjnft1ffFTeHZjzCAi9DS4cFqgS6mlHUGDhAmQQ8YSDOseeyjXoUcrVngYkoONVdQc2wbiW9KKYTqe/ZsRYGEZi4sNyLX8RsUlPkJXHNkTP/AgR1BTqh1IphS6xGIwbY9LLsqwT6Mq57i5NRkROVSONQm9fQQJzgSKND4sho6n+sP4Fq2N6GGOwo20mujTnb3mamzAC/zKLHDWAyK1YIPA6tWAysXLKhKMtPE=
  app: participedia-api
  on:
    repo: participedia/api
